# Generated by Django 4.1.5 on 2023-01-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="title",
            field=models.CharField(default="bob", max_length=200),
            preserve_default=False,
        ),
    ]
